#!/bin/sh
# Embed the front-end (web/) into web_assets.h as C byte arrays, so the binary is a
# single self-contained artifact with no runtime file dependency. Requires `xxd`
# (ships with vim-common). Run automatically by the Makefile.
set -e
cd "$(dirname "$0")"

emit() {   # $1 = file, $2 = C symbol base
  xxd -i "$1" | sed -E \
    "s/unsigned char [A-Za-z0-9_]+\[\]/unsigned char $2[]/; \
     s/unsigned int [A-Za-z0-9_]+_len/unsigned int ${2}_len/"
}

{
  echo "/* AUTO-GENERATED by gen_assets.sh from web/ — do not edit. */"
  echo "#ifndef AIRPOC_WEB_ASSETS_H"
  echo "#define AIRPOC_WEB_ASSETS_H"
  emit web/index.html asset_index_html
  emit web/app.css    asset_app_css
  emit web/app.js     asset_app_js
  echo "#endif"
} > web_assets.h

echo "gen_assets: wrote web_assets.h"
